---
- hosts: localhost
  vars:
    digital_ocean_access_token: "{{ lookup('env', 'DIGITAL_OCEAN_ACCESS_TOKEN') }}"
    digital_ocean_image: "{{ lookup('env', 'DIGITAL_OCEAN_IMAGE') }}"
    ssh_pub_key: "{{ lookup('env', 'DIGITAL_OCEAN_PUB_KEY') }}"
  tasks:
    - name: add ssh key to digital ocean
      digital_ocean:
        state: present
        command: ssh
        name: review_app_ssh_key
        ssh_pub_key: "{{ ssh_pub_key }}"
        api_token: "{{ digital_ocean_access_token }}"
      register: ssh_key_id

    - name: create review app droplet
      digital_ocean:
        state: present
        command: droplet
        name: mydroplet
        api_token: "{{ digital_ocean_access_token }}"
        size_id: s-1vcpu-1gb
        region_id: nyc1
        image_id: "{{ digital_ocean_image }}"
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.droplet.id }}"

    - debug:
        msg: "IP is {{ my_droplet.droplet.ip_address }}"

